version: '3.9'

services:
  weatherapp:
    container_name: weatherapp
    image: weatherapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5004:5004
    env_file:
      - .env
    restart: always